version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: get Node version (build)
          command: node -v
          
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: get Node version (Test)
          command: node -v
